# Generated by Django 4.1.3 on 2023-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donations_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donations',
            field=models.CharField(default='{"to":None,"status":In Progress,"email":None,"phone":None}', max_length=10000000),
        ),
    ]
