# Generated by Django 4.1.3 on 2023-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_donations_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donations',
            field=models.CharField(default='{"to":None,"status":"In Progress","email":None,"phone":None}', max_length=10000000),
        ),
    ]
