# Generated by Django 4.1.3 on 2023-02-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_donations_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='phone',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
