# Generated by Django 4.1.3 on 2023-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_donations_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donations',
            field=models.CharField(default='{"to":[],"status":"In Progress","email":[],"phone":[],"date":[]}', max_length=10000000),
        ),
    ]
